### ISSUE TITLE
What about Bebra technologies in your project?

### ISSUE THREAD

**Issue by CatOrLeader** [danmaninc/F23-Optimization-Task1#1]
Hello, it's Bebra CO. We want to cooperate with you to introduce a new, alternative simplex method that will be based on the Bebra Elimination. How are you looking at this? We're waiting for your answer! Our email is bebraSupport@innopolis.bebraversity.

**Comment by dinaraparanid** [comment]
Greetings! Currently, we are working on the new project deeply connected to the "Theory of Quantum Bebra", proposed by Ar$ex\\@gachi.com\. We are looking forward for collaborators and sponsors! If you are interested, please review the file below. 

Thank you for your time and patience!
[text.txt](https://github.com/danmaninc/F23-Optimization-Task1/files/13034241/text.txt)

$impFlexAboba@technopolis.controversity
